### PR TITLE
fix(autoload): register fallback autoload as needed

### LINKED ISSUE #254: autoload.php is not present in soil 4.0
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

This line in the new version: `require_once __DIR__ . '/vendor/autoload.php';` asks for a autoload.php located in plugins/soil/vendor/autoload.php which is not present. Throws error on activation:  

> require_once(/srv/www/example.com/current/web/app/plugins/soil/vendor/autoload.php): failed to open stream: No such file or directory

## Steps to reproduce

1. [First step]
composer require roots/soil from bedrock dir
2. [Second step]
wp plugin active soil

## Versions

4.0

### PR DESCRIPTION
**Pull request by QWp6t**
Closes #254.

To test: clone repo, don't run composer. Soil should still work.

### CODE REVIEW

File: soil.php [hunk 1]
```diff
@@ -4,7 +4,7 @@
  * Plugin Name:        Soil
  * Plugin URI:         https://roots.io/plugins/soil/
  * Description:        A collection of modules to apply theme-agnostic front-end modifications to WordPress.
- * Version:            4.0.0
+ * Version:            4.1.0
```
Comment (swalkinshaw) [inline soil.php:7]: should this be a minor patch version?
